### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by rluders** [Projeto-Pindorama/libcmon#2]
https://github.com/Projeto-Pindorama/libcmon/blob/1c5ec7517a664882153fe60ae2a8736859d54602/fdisk-list.go#L16

Seria bom tratar os erros aqui:

```go
disks, err := disks.GetAllDisksInfo()
if err != nil {
    fmt.Printf("Erro to get disk info: %v\n", err)
    return
}
```

**Comment by takusuman** [comment]
Mesma coisa que disse na #5. Extremamente válido, mas por ora quero arrumar a biblioteca em si.
