### ISSUE TITLE
Encapsulate helper do calculate `bytesToGiB`

### ISSUE THREAD

**Issue by rluders** [Projeto-Pindorama/libcmon#3]
https://github.com/Projeto-Pindorama/libcmon/blob/1c5ec7517a664882153fe60ae2a8736859d54602/fdisk-list.go#L24

You can make it better with:

```go
func bytesToGiB(bytes int64) float32 {
    return float32(bytes) / float32(1024*1024*1024)
}
```

**Comment by takusuman** [comment]
I think we can play more with this idea.
Maybe I can borrow a concept I've made at Copacabana's build system and bring it here. Just a moment.

**Comment by takusuman** [comment]
This is fixed by https://github.com/Projeto-Pindorama/libcmon/blob/master/porcelana/units.go.
