### ISSUE TITLE
Strncmp refactoring

### ISSUE THREAD

**Issue by rluders** [Projeto-Pindorama/libcmon#6]
https://github.com/Projeto-Pindorama/libcmon/blob/1c5ec7517a664882153fe60ae2a8736859d54602/bass/strcmp.go#L13

Aquela `Strcmp` não faz o menor sentido, apenas usar `==` é muito mais idiomático, de resto:

```go
func Strncmp(s1, s2 string, upto uint) bool {
	minLen := int(upto)
	if len(s1) < minLen {
		minLen = len(s1)
	}
	if len(s2) < minLen {
		minLen = len(s2)
	}

	return s1[:minLen] == s2[:minLen]
}
```

**Comment by takusuman** [comment]
> Aquela Strcmp não faz o menor sentido, apenas usar == é muito mais idiomático

Certo. Já estou usando ``==`` no código inteiro, aquilo foi mais uma comodidade que eu criei porque, como comentei na He4rt, estou vindo de C recentemente e peguei alguns hábitos --- maus ou bons --- no caminho.

**Comment by takusuman** [comment]
> de resto: [...]

Irei reescrever essa função agora. Obrigado.
