### ISSUE TITLE
You can improve the Walk

### ISSUE THREAD

**Issue by rluders** [Projeto-Pindorama/libcmon#7]
https://github.com/Projeto-Pindorama/libcmon/blob/1c5ec7517a664882153fe60ae2a8736859d54602/bass/walk.go#L13

Aqui da pra melhorar bastante. Vou listar alguns problemas.

1. Validação de argumentos
**Problema**: A validação de argumentos em Walk não cobre todos os cenários. Se place[0] (quantidade de bytes a ler) for negativo, isso pode causar comportamentos inesperados.
**Solução**: Adicionar validações mais robustas para evitar valores inválidos.

2. Buffers
**Problema**: Em Walk, o buffer é alocado para ler um byte por vez, o que é ineficiente para arquivos grandes.
**Solução**: Usar um buffer maior para reduzir o número de chamadas a Read.

3. Redundância
**Problema**: As funções compartilham lógica semelhante (ex.: manipulação de place, leitura de bytes).
**Solução**: Extrair lógica comum em funções auxiliares.

4.  Uso de bytes.Compare
`bytes.Compare` pode ser substituído por `bytes.Equal`, que é mais claro para verificar igualdade.

Tem outras coisas pequenas que podem ser melhoradas, mas acho que essas são as principais.

**Comment by takusuman** [comment]
Beleza, vou pegar essa issue para resolver primeiro --- apesar de ser a última.

> Problema: A validação de argumentos em Walk não cobre todos os cenários. Se place[0] (quantidade de bytes a ler) for negativo, isso pode causar comportamentos inesperados.

Primeiramente, é isso que se espera dessa função, quis fazer um comportamento similar a uma outra cujo nome não me recordo em que um número negativo fazia a função rodar até o fim da _string_, enquanto um número positivo fazia-a rodar até tal número. Salvo engano, era algo relacionado a RegExp.
Compreendo a preocupação, mas no caso é mais um "keep it simple, stupid" que eu resolvi adotar para simplificar a lógica das coisas.

> Problema: Em Walk, o buffer é alocado para ler um byte por vez, o que é ineficiente para arquivos grandes.

Eu tentarei aumentar o tamanho do _buffer_ e ver se não quebra algo.

> Problema: As funções compartilham lógica semelhante (ex.: manipulação de place, leitura de bytes).

Isso é um bocado vago; consigo ver lugares em que _parece_ redundante mesmo sem ser, mas num geral esse código parece estar curado o suficiente para não haver tanta redundância.


> bytes.Compare pode ser substituído por bytes.Equal, que é mais claro para verificar igualdade.

Primeira coisa que farei.

**Comment by takusuman** [comment]
Não consegui resolver a questão do buffer à primeira vista. Deixarei fechado por ora para não sobrecarregar o Projects.
